run ไม่ผ่านเพราะว่า ในการเรียกใช้ withdraw ใน checkingAccount มี throws ว่า
อาจมี error เกิดขึ้น ดังนั้นจึงต้องใช้ try/catch ดัง error ที่จะเกิด